// <auto-generated />
using System;
using FCGCatalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FCGCatalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogoDbContext))]
    partial class CatalogoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FCGCatalog.Domain.Entities.BibliotecaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_compra");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogo_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_biblioteca_usuario_usuario_id");

                    b.HasIndex("UsuarioId", "JogoId")
                        .IsUnique()
                        .HasDatabaseName("ux_biblioteca_usuario_jogo");

                    b.ToTable("biblioteca_usuarios", (string)null);
                });

            modelBuilder.Entity("FCGCatalog.Domain.Entities.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_lancamento");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("jogos", (string)null);
                });

            modelBuilder.Entity("FCGCatalog.Domain.Entities.BibliotecaUsuario", b =>
                {
                    b.HasOne("FCGCatalog.Domain.Entities.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("FCGCatalog.Domain.Entities.Jogo", b =>
                {
                    b.OwnsOne("FCGCatalog.Domain.ValueObjects.Preco", "Preco", b1 =>
                        {
                            b1.Property<Guid>("JogoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("preco");

                            b1.HasKey("JogoId");

                            b1.ToTable("jogos");

                            b1.WithOwner()
                                .HasForeignKey("JogoId");
                        });

                    b.Navigation("Preco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
